import {
  Banknote,
  BookOpen,
  Building2,
  Factory,
  FileText,
  IndianRupee,
  LayoutDashboard,
  Package,
  Receipt,
  ShoppingCart,
  Trash2,
  TrendingUp,
  UserCog,
  Users,
  Warehouse,
  Wrench,
} from "lucide-react";

export const navItems = [
  { to: "/", label: "Dashboard", icon: LayoutDashboard },
  { to: "/sales", label: "Sales", icon: TrendingUp },
  { to: "/purchase", label: "Purchase", icon: ShoppingCart },
  { to: "/investments", label: "One-time investment", icon: Wrench },
  { to: "/inventory", label: "Inventory", icon: Warehouse },
  { to: "/raw-material", label: "Raw material", icon: Factory },
  { to: "/cash", label: "Cash", icon: Banknote },
  { to: "/bank", label: "Bank", icon: Building2 },
  { to: "/gst", label: "GST", icon: Receipt },
  { to: "/profit-loss", label: "Profit & Loss", icon: IndianRupee },
  { to: "/customers", label: "Customers", icon: Users },
  { to: "/ledger", label: "Ledger", icon: BookOpen },
  { to: "/products", label: "Products", icon: Package },
  { to: "/reports", label: "Reports", icon: FileText },
  { to: "/users", label: "Users", icon: UserCog, adminOnly: true },
  { to: "/recycle-bin", label: "Recycle Bin", icon: Trash2, adminOnly: true },
] as const;
