import {
  Banknote,
  Building2,
  LayoutDashboard,
  Package,
  Receipt,
  ShoppingCart,
  TrendingUp,
  Truck,
  Users,
  Warehouse,
  FileText,
  Trash2,
  UserCog,
} from "lucide-react";

export const navItems = [
  { to: "/", label: "Dashboard", icon: LayoutDashboard },
  { to: "/sales", label: "Sales", icon: TrendingUp },
  { to: "/purchase", label: "Purchase", icon: ShoppingCart },
  { to: "/inventory", label: "Inventory", icon: Warehouse },
  { to: "/cash", label: "Cash", icon: Banknote },
  { to: "/bank", label: "Bank", icon: Building2 },
  { to: "/gst", label: "GST", icon: Receipt },
  { to: "/customers", label: "Customers", icon: Users },
  { to: "/vendors", label: "Vendors", icon: Truck },
  { to: "/products", label: "Products", icon: Package },
  { to: "/reports", label: "Reports", icon: FileText },
  { to: "/users", label: "Users", icon: UserCog, adminOnly: true },
  { to: "/recycle-bin", label: "Recycle Bin", icon: Trash2, adminOnly: true },
] as const;
