-- Block Supabase PostgREST (anon/authenticated) from ERP tables.
-- Prisma connects as postgres (table owner) and is unaffected by RLS.

ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Customer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Vendor" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Product" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductSizeStock" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SalesInvoice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SalesInvoiceItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PurchaseBill" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PurchaseBillItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PurchaseAttachment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StockMovement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PaymentReceipt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VendorPayment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LedgerEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RawMaterialBill" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RawMaterialBillItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RawMaterialPayment" ENABLE ROW LEVEL SECURITY;
